### ISSUE TITLE
sendItem() ->query has static token_id and to address

### ISSUE THREAD

**Issue by k0dlaty** [MyMetaverse/MetaBasket#1]
https://github.com/MyMetaverse/MetaBasket/blob/2069fc4156195a382ab0fe7ba2402a176cc43f83/includes/EnjinAPI.php#L97

$query = '
		advancedSendAll {
		  CreateEnjinRequest(
			identityId: ' . $identity_id . ', 
			type: ADVANCED_SEND, 
			appId: ' . $appID . ', 
			advanced_send_token_data: {
			  transfers: [
				{
				  token_id: "108000000000020a", 
				  token_index: "0",
				  to: "0xB34A5b5b52517c8502B46503b8F194Be65a4DD8a", 
				  value: "1"
				}
			  ]
			}
		  ) {
			id
			encodedData
			transactionId
		  }
		}
		';

**Comment by Geekxboy** [comment]
This has been resolved in the latest revision
